name: tennis_scoreboard
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  intl: ^0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  build_runner:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/player-placeholder.png

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf        
        - asset: assets/fonts/Gilroy/Gilroy-Thin.ttf
          weight: 300
